version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres
      POSTGRES_DB: job_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  job_service:
    build: .
    container_name: job_microservice
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:Postgres%40@my_postgres_db:5432/job_db # ✅ Fixed encoding and DB name

  auth_postgres:
    image: postgres:latest
    container_name: my_auth_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres@71
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  auth_service:
    build: ./auth_service
    container_name: auth_microservice
    ports:
      - "3001:3001"
    depends_on:
      - auth_postgres
    environment:
      DATABASE_URL: postgres://postgres:Postgres%40@my_auth_db:5432/auth_db # ✅ Fixed encoding and DB name

volumes:
  postgres_data:
  auth_postgres_data:
