version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres@71
      POSTGRES_DB: job_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: job_microservice
    ports:
      - "3000:3000"
    depends_on:
      - postgres # ✅ Fixed the service name
    environment:
      DATABASE_URL: postgres://postgres:Postgres@71@postgres:5432/job_db # ✅ Fixed encoding and DB name

volumes:
  postgres_data:
