name: Multi Service Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-auth-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: auth_service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Adjust as needed

      - name: Install dependencies
        run: npm install

      - name: Set environment variables (SQLite Test)
        run: echo "NODE_ENV=test" >> $GITHUB_ENV

      - name: Run tests
        run: npm test

  test-job-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: job_service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
      - name: Set environment variables (SQLite Test)
        run: echo "NODE_ENV=test2" >> $GITHUB_ENV
      - name: Run tests
        run: npm test

  notify-discord:
    runs-on: ubuntu-latest
    needs: [test-auth-service, test-job-service] # Waits for tests to complete
    steps:
      - name: Notify Discord
        uses: Ilshidur/action-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "🚀 GitHub Action completed for **${{ github.repository }}**! Check details: [View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
